// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::FeederJag = NULL;
CANJaguar* RobotMap::FeederMotorJag = NULL;
CANJaguar* RobotMap::driveTrainLeft_Front = NULL;
CANJaguar* RobotMap::driveTrainLeft_Rear = NULL;
CANJaguar* RobotMap::driveTrainRight_Front = NULL;
CANJaguar* RobotMap::driveTrainRight_Rear = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive41 = NULL;
Solenoid* RobotMap::CatapultA = NULL;
Solenoid* RobotMap::CatapultB = NULL;
Solenoid* RobotMap::CatapultLatchA = NULL;
Solenoid* RobotMap::CatapultLatchB = NULL;

Compressor* RobotMap::PneumaticsRobotCompressor = NULL;

AnalogChannel* RobotMap::PressureSensor = NULL;
//Not needed
//DigitalInput* RobotMap::HullSensor1 = NULL;
//DigitalInput* RobotMap::HullSensor2 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	//Practice Chassie
	FeederJag = new CANJaguar(5);
	FeederMotorJag = new CANJaguar(3);
	//Competetion Chassi
	//FeederJag = new CANJaguar(3);
	//FeederMotorJag = new CANJaguar(5);
	
	driveTrainLeft_Front = new CANJaguar(9);
	driveTrainLeft_Rear = new CANJaguar(6);
	driveTrainRight_Front = new CANJaguar(8);
	driveTrainRight_Rear = new CANJaguar(2);
	driveTrainRight_Rear->Get();
	
	driveTrainRobotDrive41 = new RobotDrive(driveTrainLeft_Front, driveTrainLeft_Rear,
              driveTrainRight_Front, driveTrainRight_Rear);
	
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor,true);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearLeftMotor,false);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor,true);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontLeftMotor,false);
	
	driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.2);
        driveTrainRobotDrive41->SetMaxOutput(1.0);
        
    //Hull Effect Sensors
   //Not needed
   // HullSensor1 = new DigitalInput(2);
   // HullSensor2 = new DigitalInput(3);
    //Solenoid code
    CatapultA = new Solenoid(3);
    CatapultB = new Solenoid(4);
    CatapultLatchA = new Solenoid(1);
    CatapultLatchB = new Solenoid(2);
    	
    //Compressor code
    PneumaticsRobotCompressor = new Compressor(1,1);
    PressureSensor = new AnalogChannel(1);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
