// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::driveTrainLeft_Front = NULL;
CANJaguar* RobotMap::driveTrainLeft_Rear = NULL;
CANJaguar* RobotMap::driveTrainRight_Front = NULL;
CANJaguar* RobotMap::driveTrainRight_Rear = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive41 = NULL;
Solenoid* RobotMap::PneumaticsBandPullerA = NULL;
Solenoid* RobotMap::PneumaticsBandPullerB = NULL;

Solenoid* RobotMap::PneumaticsBandLatchA = NULL;
Solenoid* RobotMap::PneumaticsBandLatchB = NULL;

Compressor* RobotMap::PneumaticsRobotCompressor = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTrainLeft_Front = new CANJaguar(3);
	driveTrainLeft_Rear = new CANJaguar(9);
	driveTrainRight_Front = new CANJaguar(4);
	driveTrainRight_Rear = new CANJaguar(5);
	
	driveTrainRobotDrive41 = new RobotDrive(driveTrainLeft_Front, driveTrainLeft_Rear,
              driveTrainRight_Front, driveTrainRight_Rear);
	
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor,false);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearLeftMotor,false);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor,true);
	driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontLeftMotor,false);
	
	driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.2);
        driveTrainRobotDrive41->SetMaxOutput(1.0);
        
    //Solenoid code
    PneumaticsBandPullerA = new Solenoid(1);
    PneumaticsBandPullerB = new Solenoid(2);
    PneumaticsBandLatchA = new Solenoid(3);
    PneumaticsBandLatchB = new Solenoid(4);
    //Compressor code
    PneumaticsRobotCompressor = new Compressor(1,1);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
