// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AngleDown.h"
#include "Commands/AngleUp.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Backward.h"
#include "Commands/Foward.h"
#include "Commands/Shoot.h"
#include "Commands/Stop.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick = new Joystick(2);
	
	shootButton = new JoystickButton(joystick, 1);
	shootButton->WhenPressed(new Shoot());
	fowardButton = new JoystickButton(joystick, 2);
	fowardButton->WhenPressed(new Foward());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Angle Down", new AngleDown());

	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("Angle Up", new AngleUp());

	SmartDashboard::PutData("Shoot", new Shoot());

	SmartDashboard::PutData("Foward", new Foward());

	SmartDashboard::PutData("Backward", new Backward());

	SmartDashboard::PutData("Stop", new Stop());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick() {
	return joystick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
