// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::driveTrainCANFrontLeft = NULL;
CANJaguar* RobotMap::driveTrainCANFrontRight = NULL;
CANJaguar* RobotMap::driveTrainCANBackLeft = NULL;
CANJaguar* RobotMap::driveTrainCANBackRight = NULL;
DigitalInput* RobotMap::shooterAngleLimit = NULL;
CANJaguar* RobotMap::shooterShooterOne = NULL;
CANJaguar* RobotMap::shooterShooterTwo = NULL;
CANJaguar* RobotMap::shooterAngle_Lift = NULL;
Servo* RobotMap::shooterLauncher = NULL;
CANJaguar* RobotMap::loaderBelt = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainCANFrontLeft = new CANJaguar(2);
	
	
	driveTrainCANFrontRight = new CANJaguar(3);
	
	
	driveTrainCANBackLeft = new CANJaguar(4);
	
	
	driveTrainCANBackRight = new CANJaguar(5);
	
	
	shooterAngleLimit = new DigitalInput(1, 1);
	lw->AddSensor("Shooter", "Angle Limit", shooterAngleLimit);
	
	shooterShooterOne = new CANJaguar(6);
	
	
	shooterShooterTwo = new CANJaguar(7);
	
	
	shooterAngle_Lift = new CANJaguar(8);
	
	
	shooterLauncher = new Servo(1, 1);
	lw->AddActuator("Shooter", "Launcher", shooterLauncher);
	
	loaderBelt = new CANJaguar(9);
	
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
